parent_path: '../config_default.yaml'

train_path: '/home/chouheiwa/machine_learning/dataset/ISIC2018/Train/ISIC2018_Task1-2_Training_Input'
valid_path: '/home/chouheiwa/machine_learning/dataset/ISIC2018/Validation/ISIC2018_Task1-2_Validation_Input'
test_path: '/home/chouheiwa/machine_learning/dataset/ISIC2018/Test/ISIC2018_Task1-2_Test_Input'
tensorboard_path: '/home/chouheiwa/tf-logs/UNet'