type: 'ddti-task'
root_path: './' # Need to set the real dataset path

image_size: 256

origin_image:
  size: [ 2000, 3008 ] # [ height, width ]

processed_image:
  size: null # [ height, width ]

batch_size: 10
num_workers: 8
augmentation_prob: 0.4

batch_dice: False
use_k_fold: True